export const GET_MOVIES = 'GET_MOVIES';
export const LOAD_MOVIES = 'LOAD_MOVIES';
export const RESET_ALL = 'RESET_ALL';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const ADD_TO_SUGGESTIONS = 'ADD_TO_SUGGESTIONS';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
